### ISSUE TITLE
No module named scrapydo

### ISSUE THREAD

**Issue by Rayn-liuwei** [awolfly9/IPProxyTool#10]
Traceback (most recent call last):
  File "ipproxytool.py", line 7, in <module>
    import run_validator
  File "/opt/software/IPProxyTool/run_validator.py", line 8, in <module>
    import scrapydo
ImportError: No module named scrapydo

请问，这个模块从哪里可以下载到？？

**Comment by awolfly9** [comment]
直接用 python 的包管理器 pip 就可以下载到

```
pip install scrapydo
```
