### ISSUE TITLE
运行脚本ipproxytool.py报错：File "ipproxytool.py", line 7, in <module>

### ISSUE THREAD

**Issue by hcw2175** [awolfly9/IPProxyTool#15]
```bash
$ python ipproxytool.py

Traceback (most recent call last):
  File "ipproxytool.py", line 7, in <module>
    import run_validator
  File "/Users/hucw/DevTools/IPProxyTool/run_validator.py", line 8, in <module>
    import scrapydo
ImportError: No module named scrapydo
```

**Comment by hcw2175** [comment]
抱歉，不同python，应该是依赖出问题
