### ISSUE TITLE
运行run_server.py时报错~~

### ISSUE THREAD

**Issue by llllllucas** [awolfly9/IPProxyTool#28]
TypeError: type object argument after ** must be a mapping, not NoneType

macos
python3.6

**Comment by projectmanagerment** [comment]
[root@cloud IPProxyTool-master]# python ipproxytool.py 
Traceback (most recent call last):
  File "ipproxytool.py", line 7, in <module>
    import run_validator
  File "/usr/local/IPProxyTool/IPProxyTool-master/run_validator.py", line 8, in <module>
    import scrapydo
ImportError: No module named scrapydo
