### ISSUE TITLE
运行 ipproxytool.py 出错

### ISSUE THREAD

**Issue by yesdino** [awolfly9/IPProxyTool#29]
运行启动脚本 ipproxytool.py 时，报错。
[root@localhost IPProxyTool]# python3 ipproxytool.py
Traceback (most recent call last):
  File "ipproxytool.py", line 8, in <module>
    import run_validator_async
  File "/media/sf_LinuxShare/IPProxyTool/run_validator_async.py", line 8, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'

然后我用 pip 安装 aiohttp 之后运行再次报错：
[root@localhost IPProxyTool]# python3 ipproxytool.py
Traceback (most recent call last):
  File "ipproxytool.py", line 30, in <module>
    run_validator.validator()
  File "/media/sf_LinuxShare/IPProxyTool/run_validator.py", line 33, in validator
    module = import_module(path)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 936, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 936, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 945, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ipproxytool.spiders'; 'ipproxytool' is not a package
Traceback (most recent call last):
  File "run_crawl_proxy.py", line 6, in <module>
    import scrapydo
ImportError: No module named scrapydo
[root@localhost IPProxyTool]# Traceback (most recent call last):
  File "run_server.py", line 8, in <module>
    from server import dataserver
  File "/media/sf_LinuxShare/IPProxyTool/server/dataserver.py", line 9, in <module>
    from sql import SqlManager
  File "/media/sf_LinuxShare/IPProxyTool/sql/__init__.py", line 4, in <module>
    from sql.mysql import MySql
  File "/media/sf_LinuxShare/IPProxyTool/sql/mysql.py", line 6, in <module>
    import pymysql
ImportError: No module named pymysql

因为最近需要用到提取ip，所以想问下是不是我的安装步骤哪里不对。
我用的是centos6.5, python3.6.1

**Comment by asthman666** [comment]
报错信息ImportError: No module named pymysql，没有安装pymysql

你需要pip install -r requirements.txt安装所有需要的包
