### ISSUE TITLE
参数错误attr() got an unexpected keyword argument 'type'

### ISSUE THREAD

**Issue by HeiShanLaoYao889** [awolfly9/IPProxyTool#30]
Traceback (most recent call last):
  File "/*******/python/IPProxyTool/ipproxytool.py", line 8, in <module>
    import run_validator_async
  File "/*******/python/IPProxyTool/run_validator_async.py", line 8, in <module>
    import aiohttp
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import *  # noqa
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/client.py", line 18, in <module>
    from . import client_exceptions, client_reqrep
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 17, in <module>
    from . import hdrs, helpers, http, multipart, payload
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/helpers.py", line 166, in <module>
    @attr.s(frozen=True, slots=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/helpers.py", line 168, in ProxyInfo
    proxy = attr.ib(type=str)
TypeError: attr() got an unexpected keyword argument 'type'

**Comment by YXCQU** [comment]
pip install aiohttp==2.3.7
不要用最新的版本
