### ISSUE TITLE
同样遇到这个问题

### ISSUE THREAD

**Issue by kobunketsu** [awolfly9/IPProxyTool#31]
Traceback (most recent call last):
  File "ipproxytool.py", line 7, in <module>
    import run_validator
  File "/usr/local/IPProxyTool/IPProxyTool-master/run_validator.py", line 8, in <module>
    import scrapydo
ImportError: No module named scrapydo

_Originally posted by @projectmanagerment in https://github.com/awolfly9/IPProxyTool/issues/28#issuecomment-383538546_

**Comment by awolfly9** [comment]
需要安装 scrapydo
