### ISSUE TITLE
ImportError: No module named pymongo

### ISSUE THREAD

**Issue by bfbd888** [awolfly9/IPProxyTool#6]
`sudo apt-get install docker.io`
... 
` sudo docker run -it --name=proxy proxy`

```
Traceback (most recent call last):
  File "ipproxytool.py", line 7, in <module>
    import run_validator
  File "/home/run_validator.py", line 11, in <module>
    from ipproxytool.spiders.validator.douban import DoubanSpider
  File "/home/ipproxytool/spiders/validator/douban.py", line 3, in <module>
    from validator import Validator
  File "/home/ipproxytool/spiders/validator/validator.py", line 10, in <module>
    from sql import SqlManager
  File "/home/sql/__init__.py", line 5, in <module>
    from mongodb import Mongodb
  File "/home/sql/mongodb.py", line 4, in <module>
    import pymongo
ImportError: No module named pymongo

```

**Comment by awolfly9** [comment]
@bfbd888 这个是我今天刚上传的支持 mongodb 数据库需要用到的包，用 pip 安装一下就行了：
pip install pymongo

**Comment by bfbd888** [comment]
我在requestsment.txt中添加了pymongo，然后重新build就好了，感谢。
