### ISSUE TITLE
sql包下的module引用错误

### ISSUE THREAD

**Issue by MrKang** [awolfly9/IPProxyTool#7]
在运行validator的时候根据日志可以看到用于验证proxy的spider(百度，拉勾，httpbin等)都会有引用问题，具体log如下
```python
File "run_spider.py", line 33, in <module>
    runspider(name)
  File "run_spider.py", line 19, in runspider
    process = CrawlerProcess(get_project_settings())
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 243, in __init__
    super(CrawlerProcess, self).__init__(settings)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 134, in __init__
    self.spider_loader = _get_spider_loader(settings)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 330, in _get_spider_loader
    return loader_cls.from_settings(settings.frozencopy())
  File "/usr/local/lib/python2.7/dist-packages/scrapy/spiderloader.py", line 61, in from_settings
    return cls(settings)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/spiderloader.py", line 25, in __init__
    self._load_all_spiders()
  File "/usr/local/lib/python2.7/dist-packages/scrapy/spiderloader.py", line 47, in _load_all_spiders
    for module in walk_modules(name):
  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/misc.py", line 69, in walk_modules
    mods += walk_modules(fullpath)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/misc.py", line 71, in walk_modules
    submod = import_module(fullpath)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/IPProxyTool/ipproxytool/spiders/proxy/basespider.py", line 10, in <module>
    from sql import SqlManager
  File "/opt/IPProxyTool/sql/__init__.py", line 3, in <module>
    from sql.sql import Sql
```
运行环境：
Ubuntu 16
python3
已安装requirement.txt中的东西(确认是pip3安装的)

**Comment by MrKang** [comment]
找了之前的py2.7版的运行了下没问题。不知道是不是我机子问题，机子上的py3.5好像是系统预装的

**Comment by awolfly9** [comment]
你好，感谢你的反馈。


我是在 python3.6.1 下运行测试的。目前测试没有发现问题。

如果你依旧不能够解决，可以尝试更改 sql 模块下的引用关系。


在不能够，就加我微信





2017-07-11 16:59 GMT+08:00 Kang <notifications@github.com>:

**Comment by meihuanyu** [comment]
app$ python3 ipproxytool.py 
Traceback (most recent call last):
  File "run_crawl_proxy.py", line 6, in <module>
    import scrapydo
ImportError: No module named scrapydo
Traceback (most recent call last):
  File "run_server.py", line 8, in <module>
    from server import dataserver
  File "/Users/app/Applications/IPProxyTool/server/dataserver.py", line 9, in <module>
    from sql import SqlManager
  File "/Users/app/Applications/IPProxyTool/sql/__init__.py", line 3, in <module>
    import sql.sql
ImportError: No module named sql
^CTraceback (most recent call last):
  File "ipproxytool.py", line 26, in <module>
    run_validator.validator()
  File "/Users/app/Applications/IPProxyTool/run_validator.py", line 44, in validator

报错的这些包我都装了  好奇怪 单独在导入这些包都没问题

**Comment by awolfly9** [comment]
@meihuanyu scrapydo 这是一个外部依赖包，需要单独安装


关于大家反馈的 
import sql.sql
ImportError: No module named sql
我会在近期进行调整修改。

**Comment by awolfly9** [comment]
@MrKang 
@meihuanyu 

关于 sql 引用报错已经提交了更新。

**Comment by meihuanyu** [comment]
解决了  。。。谢谢啦
